@TecVentas_HostAddress = http://localhost:5020


###  Login

POST {{TecVentas_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

### Token de prueba 
@TecVentas_AdminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc4Mjc5ODQ4NiwiaXNzIjoiTWlBUEkiLCJhdWQiOiJNaUFQSVVzdWFyaW9zIn0.urP_Zz43BVzJDFS7-8nFN2RO3lbADswANe1TvcZQM0I

### Crear Usuario
POST {{TecVentas_HostAddress}}/api/auth/users
Content-Type: application/json
Authorization: Bearer {{TecVentas_AdminToken}}

{
  "nombre": "Luis",
  "username": "hawk",
  "password": "1234",
  "correo": "hawk@com.com",
  "telefono": "7777-8888",
  "role": "admin"
}

### Listar Usuarios
GET {{TecVentas_HostAddress}}/api/auth/users
Authorization: Bearer {{TecVentas_AdminToken}}
Accept: application/json

### Actualizar Usuario
PUT {{TecVentas_HostAddress}}/api/auth/users/1
Content-Type: application/json
Authorization: Bearer {{TecVentas_AdminToken}}

{
  "id": 1,
  "nombre": "Usuario Actualizado",
  "username": "user1",
  "password": "1234",
  "correo": "user@new.com",
  "telefono": "9999-9999",
  "role": "User"
}

### Eliminar Usuario
DELETE {{TecVentas_HostAddress}}/api/auth/users/3
Authorization: Bearer {{TecVentas_AdminToken}}



### crear Producto
POST {{TecVentas_HostAddress}}/api/productos
Content-Type: application/json

{
  "nombre": "Xbox one S",
  "precio": 400000
}
###   Listar Productos
GET {{TecVentas_HostAddress}}/api/productos
Accept: application/json

### Actualizar Producto
PUT {{TecVentas_HostAddress}}/api/productos/1
Content-Type: application/json

{
  "id": 1,
  "nombre": "Laptop Acer Aspire 3 - Nueva",
  "precio": 340000
}

### Eliminar Producto
DELETE {{TecVentas_HostAddress}}/api/productos/3


### VENTAS


### Crear Venta
POST {{TecVentas_HostAddress}}/api/ventas
Content-Type: application/json

{
  "userId": 3,
  "productoId": 1,
  "cantidad": 3
}

### Listar Ventas
GET {{TecVentas_HostAddress}}/api/ventas
Accept: application/json

### Actualizar Venta
PUT {{TecVentas_HostAddress}}/api/ventas/1
Content-Type: application/json

{
  "id": 1,
  "userId": 1,
  "productoId": 1,
  "cantidad": 3
}

### Eliminar Venta
DELETE {{TecVentas_HostAddress}}/api/ventas/2


### Crear orden PayPal
POST {{TecVentas_HostAddress}}/api/paypal/create-order?amount=10
Accept: application/json




### Pagos

### Obtener todos los pagos
GET {{TecVentas_HostAddress}}/api/Pagos
Accept: application/json

###

### Crear un nuevo pago
POST {{TecVentas_HostAddress}}/api/Pagos
Content-Type: application/json

{
  "ventaId": 1,
  "clienteId": 1,
  "monto": 1500.50,
  "metodoPago": "Tarjeta",
  "fechaHora": "2026-06-29T14:30:00",
  "estado": "Completado",
  "codigoAutorizacion": "ABC123XYZ"
}

###

### Obtener un pago por ID
GET {{TecVentas_HostAddress}}/api/Pagos/1
Accept: application/json

###

### Actualizar un pago existente
PUT {{TecVentas_HostAddress}}/api/Pagos/1
Content-Type: application/json

{
  "pagoId": 1,
  "ventaId": 1,
  "clienteId": 1,
  "monto": 2000.00,
  "metodoPago": "PayPal",
  "fechaHora": "2026-06-29T15:00:00",
  "estado": "Pendiente",
  "codigoAutorizacion": "XYZ789"
}

###

### Eliminar un pago
DELETE {{TecVentas_HostAddress}}/api/Pagos/1
